Repository Sports-Matching-Service/Backend, pull requests merged in 2022-10, with the labels that each got.

#3 Feat/signup
  src/main/java/sportsmatchingservice/user/dto/UserPostDto.java
  src/main/java/sportsmatchingservice/users/controller/UserController.java
  src/main/java/sportsmatchingservice/users/domain/User.java
  src/main/java/sportsmatchingservice/users/dto/UserPostDto.java
  src/main/java/sportsmatchingservice/users/repository/UserRepository.java
  src/main/java/sportsmatchingservice/users/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#7 Feat/login
  build.gradle
  src/main/java/sportsmatchingservice/auth/dto/LoginDto.java
  src/main/java/sportsmatchingservice/auth/filter/AuthenticationFilter.java
  src/main/java/sportsmatchingservice/auth/jwt/JwtTokenizer.java
  src/main/java/sportsmatchingservice/auth/userdetails/PrincipalDetailsService.java
  src/main/java/sportsmatchingservice/auth/utils/CustomAuthorityUtils.java
  src/main/java/sportsmatchingservice/config/SecurityConfig.java
  src/main/java/sportsmatchingservice/exceptions/GeneralExceptionHandler.java
  src/main/java/sportsmatchingservice/users/controller/UserController.java
  src/main/java/sportsmatchingservice/users/domain/User.java
  src/main/java/sportsmatchingservice/users/dto/UserPostDto.java
  src/main/java/sportsmatchingservice/users/repository/UserRepository.java
  src/main/java/sportsmatchingservice/users/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement, refactor

#9 Feat/signup
  src/main/java/sportsmatchingservice/auth/controller/UserController.java
  src/main/java/sportsmatchingservice/auth/domain/User.java
  src/main/java/sportsmatchingservice/auth/dto/UserSignupDto.java
  src/main/java/sportsmatchingservice/auth/filter/AuthenticationFilter.java
  src/main/java/sportsmatchingservice/auth/repository/UserRepository.java
  src/main/java/sportsmatchingservice/auth/service/UserService.java
  src/main/java/sportsmatchingservice/auth/userdetails/PrincipalDetailsService.java
Labels: refactor

#10 JWT 검증 구현 및 예외 처리
  build.gradle
  src/main/java/sportsmatchingservice/auth/controller/UserController.java
  src/main/java/sportsmatchingservice/auth/dto/UserSignupDto.java
  src/main/java/sportsmatchingservice/auth/filter/AuthenticationFilter.java
  src/main/java/sportsmatchingservice/auth/filter/JwtVerificationFilter.java
  src/main/java/sportsmatchingservice/auth/handler/UserAccessDeniedHandler.java
  src/main/java/sportsmatchingservice/auth/handler/UserAuthenticationEntryPoint.java
  src/main/java/sportsmatchingservice/auth/handler/UserAuthenticationFailureHandler.java
  src/main/java/sportsmatchingservice/auth/handler/UserAuthenticationSuccessHandler.java
  src/main/java/sportsmatchingservice/auth/jwt/JwtTokenizer.java
  src/main/java/sportsmatchingservice/config/SecurityConfig.java
  src/main/java/sportsmatchingservice/constant/ErrorCode.java
Labels: enhancement, refactor

#11 Feat/oauth kakao
  build.gradle
  src/main/java/sportsmatchingservice/auth/controller/UserController.java
  src/main/java/sportsmatchingservice/auth/domain/User.java
  src/main/java/sportsmatchingservice/auth/dto/OauthTokenDto.java
  src/main/java/sportsmatchingservice/auth/dto/UserInfoOauthDto.java
  src/main/java/sportsmatchingservice/auth/dto/UserTokenDto.java
  src/main/java/sportsmatchingservice/auth/service/OauthKakaoService.java
  src/main/java/sportsmatchingservice/config/JsonConfig.java
  src/main/java/sportsmatchingservice/config/OauthRestTemplateConfig.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
Labels: enhancement, refactor
